- name: Check if PostgreSQL is already installed
  stat:
    path: /usr/bin/psql
  register: psql_path

- name: Install PostgreSQL 15 if not present
  when: not psql_path.stat.exists
  yum:
    name:
      - postgresql15
      - postgresql15-server
    state: present
