- name: Install PostgreSQL on Amazon Linux / RHEL
  block:
    - name: Enable the PostgreSQL repo
      command: amazon-linux-extras enable postgresql14
      args:
        creates: /etc/yum.repos.d/amzn2-extras.repo

    - name: Install PostgreSQL
      yum:
        name:
          - postgresql
          - postgresql-server
          - postgresql-contrib
        state: present
  when: ansible_os_family == "RedHat"