- name: Install PostgreSQL on Debian/Ubuntu
  apt:
    name: postgresql
    state: present
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL on RHEL/Amazon Linux
  yum:
    name: postgresql-server
    state: present
  when: ansible_os_family in ["RedHat", "Amazon"]
