- name: Check if PostgreSQL is already installed
  command: psql --version
  register: postgres_check
  ignore_errors: yes

- name: Install PostgreSQL only if not already installed
  when: postgres_check.rc != 0
  block:
    - name: Install PostgreSQL (fallback method)
      dnf:
        name:
          - postgresql14
          - postgresql14-server
        state: present
