- name: Update all packages to latest
  become: true
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: Check if PostgreSQL is already installed
  stat:
    path: /usr/bin/psql
  register: psql_path

- name: Install PostgreSQL 15 if not present
  when: not psql_path.stat.exists
  yum:
    name:
      - postgresql15
      - postgresql15-server
    state: present

- name: Initialize PostgreSQL database (only if installed)
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  when: psql_path.stat.exists

- name: Enable and start PostgreSQL service
  systemd:
    name: postgresql-15
    enabled: yes
    state: started

# -------------------------------
# Security hardening (optional but safe)
# -------------------------------

- name: Disable root SSH login (non-invasive)
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    backup: yes

- name: Restart SSH service
  become: true
  systemd:
    name: sshd
    state: restarted
    enabled: yes

# -------------------------------
# Safe user management (no existing user change)
# -------------------------------

- name: Create a dedicated deployment user (safe if doesn't exist)
  become: true
  user:
    name: sneha
    state: present
    groups: wheel
    shell: /bin/bash
    create_home: yes

