- name: Update apt cache (for Ubuntu)
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Node.js
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    apt-get install -y nodejs
  when: ansible_os_family == "Debian"
